CREATE OR REPLACE TRIGGER trg$tuning_ea_afterlogon
  AFTER logon ON DATABASE
DECLARE
  cmmd VARCHAR2(64);
BEGIN
  cmmd := 'ALTER SESSION SET CURSOR_SHARING = SIMILAR';
  EXECUTE IMMEDIATE cmmd;

  cmmd := 'ALTER SESSION SET CREATE_STORED_OUTLINES = TRUE';
  EXECUTE IMMEDIATE cmmd;
END;
/
